version: 0.2
env:
  secrets-manager:
    SPECTRAL_DSN: arn:aws:secretsmanager:us-east-1:308107017754:secret:spectralsecrets-OJd0QO
phases:
  build:
    commands:
      - ...
  post_build:
    commands:
      - curl -L "https://spectral-us.checkpoint.com/latest/x/sh?dsn=$SPECTRAL_DSN" | sh
      - $HOME/.spectral/spectral scan --ok --engines secrets,iac,oss --include-tags base,audit,iac
